---

# ---- Simulation settings ----

# Number of people to simulate
population_size: 100000

# Number of days to simulate
n_days: 200

# ---- Initialisation settings ----

# Proportion of population previously infected
previously_infected: 0.3

# Number of days over which these past infections have occured
n_days_init: -360

# Effective reproduction number at analysis start
r_eff: 1.0  # Calibrated in step 1

# Time window (in days) for calculating R_eff
#
# See: cran.r-project.org/web/packages/EpiEstim/vignettes/demo.html
r_eff_window: 7

# Transmission probability at maximum infecitivty, susceptibility, and seasonality
beta: 0.05

# Seasonality profile
seasonality_fn: 
  fn: "cospi"
  x:
    fn: "seq"
    from: -1
    to: 1
    length.out: 365
seasonality_scaler: 0.3

# Number of days to shift seasonality start
seasonality_shift: 120  # 0 represents mid-winter

# ---- Network structure ----

# Network structure
#
# OPTIONS: "random", "age", or "layers"
network_structure: "age"

# Network layers - only relevant if network structure is set to "layers"
#
# OPTIONS: "household", "school", and/or "workplace"
network_layers: household #, school, workplace, 

# Layer properties - only relevant if network structure is set to "layers"
layer_properties:
  household:
    distribution: "normal"
    mean: 2.5
    sd: 1.0
    age_min: 0
    age_max: Inf
    beta_scaler: 1.0
  school:
    cluster_sampling:
      method: static
      value: 10
    contacts: 3.0
    age_min: 0
    age_max: 20
    beta_scaler: 1.0
  workplace:
    cluster_sampling:
        method: static
        value: 10
    contacts: 3.0
    age_min: 21
    age_max: 65
    beta_scaler: 1.0

# Sampling technique for community layer
#
# OPTIONS: "static" or "dynamic"
community_sampling: "static"

# Countries to pull network matrix data from
contact_matrix_countries: DE, IT, FR  # ISO Alpha-2 country codes (en.wikipedia.org/wiki/ISO_3166-1_alpha-2)

# ---- Importations ----

# Importated infections per day
import_constant: 1.5  # per 100k people

# ---- Viral variants ----

# Primary variant (properties relative to prognosis probabilities)
variant_primary:
  id: delta
  name: "Delta (B.1.617.2)"
  infectivity: 1.0
  severity: 1.0
  immuno_escape: 0.0

# Novel variant properties (properties relative to primary variant)
variants_novel: 
- id: novel_variant
  name: "Novel variant template"
  import_day: 0
  import_number: 0 # Set import_number to zero to turn off novel variant importation
  infectivity: 1.0
  severity: 1.0
  immuno_escape: 0.0

# Viral load profile
viral_load_infectivity: yes
viral_load_shape_fn: 
  fn: "dgamma"
  shape: 3.0
  rate: 0.5
  
# Immunity through natural infection
acquired_immunity:
  value: 0.83
  decay_init: 180
  decay_duration: 360
  
# ---- Priority and risk groups ----

# Priority group definitions
priority_groups: 
- id: teachers
  name: "teacher == TRUE"
  priority: 1
  condition: "teacher == TRUE"
- id: above65comorb
  name: "65+ or comorbidities"
  priority: 2
  condition: "age >= 65 | comorbidities == TRUE"
- id: above5
  name: "5 - 65 year old"
  priority: 3
  condition: "age >= 5 & age < 65"
  
# Risk groups
risk_groups:
  comorbidities:
    age_lower: 0
    age_upper: 75
    probability: 0.08
  healthcare_worker:
    age_lower: 18
    age_upper: 65
    probability: 0.10

# Use random teacher sampling rather than layer-based sampling
overwrite_teacher_sampling: no

# Take out random contacts between ppl of working age rather than random contacts between adults
overwrite_workplace_sampling: no

# ---- Vaccination details ----
  
# Vaccine definition and immunity profile
vaccine_defintion:
  name: "mRNA vaccine"
  transmission_blocking: 0.85  # Proportion of efficacy that blocks transmission
  efficacy:
    fn: ["logistic_inv", "logistic_inv"]
    slope: [1.8, 1.8]
    mid: [21, 70]
    lb: [0.10, 0.10]
    ub: [0.40, 0.85]
  subsequent_dose_days: 28  # Use 0 for a single dose vaccine
  booster_efficacy:
    fn: "logistic_inv"
    slope: 1.8
    mid: 105
    lb: 0.15
    ub: 0.85
  
# Vaccination history
vaccine_history: 
- id: teachers
  init_coverage: 0.0
  init_start: 0  # Days into the past that vaccination program began
  init_end: 0       # Days into the past that vaccination program ended (set to zero if ongoing)
- id: above65comorb
  init_coverage: 0.0
  init_start: 0  # Days into the past that vaccination program began
  init_end: 0       # Days into the past that vaccination program ended (set to zero if ongoing)
- id: above5
  init_coverage: 0.0
  init_start: 0
  init_end: 0
  
# Future vaccination rollout
vaccine_rollout: 
- id: teachers
  max_coverage: 0.0
  max_start: 0  # Days into the future that vaccination scale up will began (set to zero if ongoing)
  max_end: 0   # Days into the future that vaccination scale up will reach max coverage
- id: above65comorb
  max_coverage: 0.0
  max_start: 0  # Days into the future that vaccination scale up will began (set to zero if ongoing)
  max_end: 0   # Days into the future that vaccination scale up will reach max coverage
- id: above5
  max_coverage: 0.0
  max_start: 0
  max_end: 0
  
# Vaccine booster rollout (only groups to recieve a booster need to be specified)
booster_doses: 0  # Maximum number of doses per day (per 100,000 people)
booster_rollout:
- id: teachers
  probability: 0.0   # Probability of accepting/receiving a booster dose
  cycle_period: 365  # Booster dose administered every cycle_period days
  start: 0           # When booster started to be available (-ve for past, +ve for future, 0 for start of analysis period)
  force_start: no    # Force a booster at this time regardless of when initial vaccination was (set to 'no' to turn off)
  force_end: no      # Force an end point to stop cyclic boosters (set to 'no' to turn off)
- id: above65comorb
  probability: 0.0   # Probability of accepting/receiving a booster dose
  cycle_period: 365  # Booster dose administered every cycle_period days
  start: 0           # When booster started to be available (-ve for past, +ve for future, 0 for start of analysis period)
  force_start: no    # Force a booster at this time regardless of when initial vaccination was (set to 'no' to turn off)
  force_end: no      # Force an end point to stop cyclic boosters (set to 'no' to turn off)
- id: above5
  probability: 0.0   # Probability of accepting/receiving a booster dose
  cycle_period: 365  # Booster dose administered every cycle_period days
  start: 0           # When booster started to be available (-ve for past, +ve for future, 0 for start of analysis period)
  force_start: no    # Force a booster at this time regardless of when initial vaccination was (set to 'no' to turn off)
  force_end: no      # Force an end point to stop cyclic boosters (set to 'no' to turn off)
  
# ---- Treatment details ----

# Probability of treatment given diagnosis
treatment:
- id: high_priority
  # product: "product1"
  vaccine_condition: "none"  # OPTIONS: "vaccinated", "unvaccinated", "none"
  available: 0      # Date index of when treatment becomes available for this group
  prob_mild: 0.0    # Probability of treatment if currently mild symptoms
  prob_severe: 0.0  # Probability of treatment if currently severe symptoms
  prob_crit: 0.0    # Probability of treatment if currently critical symptoms
  
- id: low_priority
  # product: "product2"
  vaccine_condition: "none"
  available: 0
  prob_mild: 0.0
  prob_severe: 0.0
  prob_crit: 0.0
  
# Delay from diagnosis to treatment effect
treat_delay: 5
  # fn: "rnorm"
  # mean: 2.0
  # sd: 1

# Treatment efficacy: reduction in probability of hospitalisation
treat_efficacy: 0.89

# Alternative way to define treatment efficacy for individual products
#
# TODO: Not yet implemented
treat_products:
- id: product1
  name: "Some treatment"
  efficacy: 0.89
- id: product2
  name: "Some other treatment"
  efficacy: 0.3

# ---- Other interventions ----

# NOTES:
#  1) Model uses either 'npi_ochi' or 'npi_effect' to define NPIs over time
#  2) If npi_ochi::use is set to 'yes', this trumps npi_layers
#  2) Whichever is used, 'npi_scaler' is used to scale the overall effect on contact reduction

# Pull OCHI data for given country
npi_ochi:
  use: no
  country: CH  # Use ISO Alpha-2 country code
  start: 2020-03-01
  
# Custom NPI effect over time in each layer
npi_layers:
- layer: household
  day1: 1.0
- layer: school
  day1: 1.0
- layer: workplace
  day1: 1.0
- layer: community
  day1: 1.0

# NPI scaling effect: applies to both 'ochi_country' and 'npi_effect'
npi_scaler: 1  # Set to 0 to turn off NPIs

# Testing and diagnosis
diagnosis_delay: 3  # Delay between symptom onset and test/diagnosis
testing:
  without_symptoms:
    sensitivity: 0.98
    probability: 0.05
    age_dist:
      fn: "dunif"
  with_symptoms:
    sensitivity: 0.98
    probability: 0.8
    age_dist:
      fn: "dunif"
  mass_testing:
    sensitivity: 0.7
    probability: 0.5  # Interpret this as 'mass testing acceptance'
    age_dist:
      fn: "dgamma"
      shape: 1.4
      rate: 1.0
    when:
      fn: "seq"
      from: 240
      to: 300
      by: 30
    coverage: 0.0

# Isolation
isolation: 
  probability: 1.0
  delay: 0
  duration: 10

# ---- Biological and epidemiological parameters ----

# Age-related probabiliy of severe disease given person is symptomatic
severe_symptom_age:
  fn: "logistic"
  slope: 6
  mid: 65
  lower: 0
  upper: 0.3
  
# Age-related probabiliy of critical disease given person is severe
critical_severe_age:
  fn: "logistic"
  slope: 6
  mid: 100
  lower: 0.05
  upper: 1.9
  
# Age-related probabiliy of death given person is critical
death_critical_age:
  fn: "logistic"
  slope: 14
  mid: 90
  lower: 0
  upper: 2
  
# Scale factors for death when critical in/out of ICU
death_critical_icu: 0.2
death_critical_non_icu:	0.95

# Probability of asymptomatic infection
proportion_asymptomatic: 0.33

# Probability of seeking care if severe
seek_hospital: 0.75

# Flag for replacing dead people
replace_dead: no

# Maximum number of infections to count per person
max_infections: 5

# Disease state durations
durations:
  latency:
    fn: "rnorm"
    mean: 4.6
    sd: 1.0
  presymptomatic:
    fn: "rnorm"
    mean: 3.0
    sd: 1.0
  infectious_mild:
    fn: "rnorm"
    mean: 6.0
    sd: 1.0
  infectious_severe: 
    fn: "rnorm"
    mean: 28.0
    sd: 1.0
  onset_to_hospital: 
    fn: "rnorm"
    mean: 13.0
    sd: 1.0
  hospital_stay: 
    fn: "rnorm"
    mean: 9.0
    sd: 1.0
  hospital_to_icu: 
    fn: "rnorm"
    mean: 2.0
    sd: 1
  icu_stay: 
    fn: "rnorm"
    mean: 7.0
    sd: 1.0
  icu_stay_death: 
    fn: "rnorm"
    mean: 6.0
    sd: 1.0
  hospital_transfer:
    fn: "rnorm"
    mean: 2.0
    sd: 1.0
  home_death: 
    fn: "rnorm"
    mean: 10.0
    sd: 1.0

# ---- Demography ----

# 90 yearly bins for ages [0-1], (1-2], ..., (89-90+] required
demography:
  age1: 0.010576408
  age2: 0.010811583
  age3: 0.010896688
  age4: 0.010928522
  age5: 0.010773903
  age6: 0.010815481
  age7: 0.010274967
  age8: 0.010219097
  age9: 0.010108005
  age10: 0.010069676
  age11: 0.009903364
  age12: 0.009705868
  age13: 0.009469393
  age14: 0.009229020
  age15: 0.009076351
  age16: 0.009010736
  age17: 0.008773611
  age18: 0.008846372
  age19: 0.008671615
  age20: 0.009396632
  age21: 0.009362849
  age22: 0.009643501
  age23: 0.010252229
  age24: 0.010779750
  age25: 0.011226064
  age26: 0.012029040
  age27: 0.013095126
  age28: 0.014302188
  age29: 0.015094119
  age30: 0.015867860
  age31: 0.016164753
  age32: 0.016590278
  age33: 0.016572737
  age34: 0.016617563
  age35: 0.016702019
  age36: 0.016664988
  age37: 0.016307028
  age38: 0.016560394
  age39: 0.016357701
  age40: 0.016451901
  age41: 0.015739878
  age42: 0.015550827
  age43: 0.014973933
  age44: 0.014849848
  age45: 0.014560101
  age46: 0.014482792
  age47: 0.014238521
  age48: 0.014273603
  age49: 0.014756298
  age50: 0.014849198
  age51: 0.015016160
  age52: 0.015149989
  age53: 0.015090871
  age54: 0.015155187
  age55: 0.014944048
  age56: 0.014902470
  age57: 0.014335320
  age58: 0.013497263
  age59: 0.012972991
  age60: 0.012270712
  age61: 0.011689269
  age62: 0.011112374
  age63: 0.010712186
  age64: 0.010361371
  age65: 0.009848143
  age66: 0.009359601
  age67: 0.008911338
  age68: 0.009055562
  age69: 0.008541034
  age70: 0.008761267
  age71: 0.008426694
  age72: 0.008458528
  age73: 0.008419548
  age74: 0.008336392
  age75: 0.008068084
  age76: 0.007888779
  age77: 0.007581491
  age78: 0.007091001
  age79: 0.006626496
  age80: 0.005900830
  age81: 0.005523380
  age82: 0.005232333
  age83: 0.004715207
  age84: 0.004624255
  age85: 0.004337107
  age86: 0.003957058
  age87: 0.003471764
  age88: 0.003121599
  age89: 0.002766237
  age90: 0.011291680

# ---- Model metrics ----

# Define model metrics to report and by which grouping
model_metrics:
  all_new_infections:
    report: yes
    by: age, priority_group, variant, layer
  new_local_infections:
    report: no
    by: none
  new_importations:
    report: no
    by: none
  confirmed:
    report: no
    by: none
  deaths:
    report: yes
    by: age, priority_group, variant
  hospital_beds:
    report: yes
    by: age, priority_group
  hospital_admissions:
    report: yes
    by: age, priority_group
  icu_beds:
    report: yes
    by: age, priority_group
  icu_admissions:
    report: no
    by: none
  currently_infected:
    report: yes
    by: none
  currently_infectious:
    report: no
    by: none
  currently_symptomatic:
    report: no
    by: none
  currently_isolated:
    report: no
    by: none
  recovered:
    report: yes
    by: none
  n_vaccinated:
    report: no
    by: priority_group
  total_vaccinated:
    report: yes
    by: priority_group
  vaccine_coverage:
    report: yes
    by: priority_group
  vaccine_coverage_pop:
    report: no
    by: none
  booster_coverage:
    report: no
    by: none
  booster_coverage_pop:
    report: no
    by: none
  booster_coverage_12m:
    report: yes
    by: priority_group
  booster_coverage_12m_pop:
    report: no
    by: none
  n_doses:
    report: yes
    by: priority_group
  total_doses:
    report: yes
    by: priority_group
  treated:
    report: yes
    by: priority_group
  treated_total:
    report: yes
    by: priority_group
  treatment_coverage:
    report: no  # Available soon!
    by: none
  treatment_coverage_pop:
    report: no  # Available soon!
    by: none
  n_infections: 
    report: yes
  variant_prevalence:
    report: yes
  R_effective:
    report: yes
  seroprevalence:
    report: yes
  pop_susceptibility:
    report: yes
  pop_prevalence:
    report: no
  seasonality:
    report: yes
  average_beta: 
    report: yes
  contact_reduction:
    report: yes
    
# ---- Calibration settings ----

# Number of contacts placeholder - this is fitted to achieve desired R_eff    
contacts: 10.0

# Define parameters to be calibrated
calibration:
- param: "contacts"
  lower: 1
  upper: 20
  
# ---- Scenarios ----

# Always run a baseline scenario
scenarios: 
- id: baseline
  name: "Baseline scenario"
