---
  
# ---------------------------------------------------------
# Epidemiological metrics
# ---------------------------------------------------------

# Reporting of new COVID-19 cases each day (includes a reporting delay)
confirmed:
  label:     "Confirmed SARS-CoV-2 cases per day"
  label_cum: "Cumulative confirmed SARS-CoV-2 cases"
  temporal:   yes
  coverage:   no
  aggregate:  yes
  cumulative: yes
  scale:      yes
  group_by:   none, age, priority_group, variant

# Reporting of new COVID-19-related deaths each day (includes a reporting delay)
deaths:
  label:     "COVID-19 deaths per day"
  label_cum: "Cumulative COVID-19 deaths"
  temporal:   yes
  coverage:   no
  aggregate:  yes
  cumulative: yes
  scale:      yes
  group_by:   none, age, priority_group, variant

# Hospital (non-ICU) beds that are in use in any one day
hospital_beds:
  label:     "COVID-19 cases in hospital"
  temporal:   yes
  coverage:   no
  aggregate:  yes
  cumulative: no
  scale:      yes
  group_by:   none, age, priority_group, variant

# ICU beds that are in use in any one day
icu_beds:
  label:     "COVID-19 cases in ICU"
  temporal:   yes
  coverage:   no
  aggregate:  yes
  cumulative: no
  scale:      yes
  group_by:   none, age, priority_group, variant

# New hospital (non-ICU) admissions each day (does not consider those leaving hospital)
hospital_admissions:
  label:     "COVID-19 hospital admissions per day"
  label_cum: "Cumulative COVID-19 hospital admissions"
  temporal:   yes
  coverage:   no
  aggregate:  yes
  cumulative: yes
  scale:      yes
  group_by:   none, age, priority_group, variant

# New ICU admissions each day (does not consider those leaving ICU)
icu_admissions:
  label:     "COVID-19 ICU admissions per day"
  label_cum: "Cumulative COVID-19 ICU admissions"
  temporal:   yes
  coverage:   no
  aggregate:  yes
  cumulative: yes
  scale:      yes
  group_by:   none, age, priority_group, variant

# Newly recovered people each day
recovered:
  label:     "New daily recovered cases"
  label_cum: "Cumulative recovered cases"
  temporal:   yes
  coverage:   no
  aggregate:  yes
  cumulative: yes
  scale:      yes
  group_by:   none, age, priority_group, variant

# Prevalence of each modelled variant over time
variant_prevalence:
  label:     "Variant prevalence"
  temporal:   yes
  coverage:   no
  aggregate:  no
  cumulative: no
  scale:      no
  group_by:   variant

# Population-level effective reproduction number
R_effective:
  label:     "Effective reproduction number"
  temporal:   yes
  coverage:   no
  aggregate:  yes
  cumulative: no
  scale:      no
  group_by:   na

# Effective contact reduction from NPIs, also considering scaling factor
contact_reduction:
  label:     "NPI contact reduction"
  temporal:   yes
  coverage:   no
  aggregate:  yes
  cumulative: no
  scale:      no
  group_by:   na

# Seasonal infectiousness over time
seasonality:
  label:     "Seasonal infectiousness (%)"
  temporal:   yes
  coverage:   no
  aggregate:  yes
  cumulative: no
  scale:      no
  group_by:   na

# Newly occuring locally-transmitted infections each day
new_local_infections:
  label:     "Daily new local infections"
  label_cum: "Cumulative local infections"
  temporal:   yes
  coverage:   no
  aggregate:  yes
  cumulative: yes
  scale:      yes
  group_by:   none, age, priority_group, variant

# New imported infections each day
new_importations:
  label:     "Daily new imported cases"
  label_cum: "Cumulative imported cases"
  temporal:   yes
  coverage:   no
  aggregate:  yes
  cumulative: yes
  scale:      yes
  group_by:   none, age, priority_group, variant

# All new infections including imported cases and variant importations
all_new_infections:
  label:     "SARS-CoV-2 infections per day"
  label_cum: "Cumulative SARS-CoV-2 infections"
  temporal:   yes
  coverage:   no
  aggregate:  yes
  cumulative: yes
  scale:      yes
  group_by:   none, age, priority_group, variant

# Total number of people currently infected
currently_infected:
  label:     "All currently infected"
  temporal:   yes
  coverage:   no
  aggregate:  yes
  cumulative: no
  scale:      yes
  group_by:   none, age, priority_group, variant

# Total number of people currently infectious
currently_infectious:
  label:     "All currently infectious"
  temporal:   yes
  coverage:   no
  aggregate:  yes
  cumulative: no
  scale:      yes
  group_by:   none, age, priority_group, variant

# Total number of people currently infected with symptoms
currently_symptomatic:
  label:     "All currently infected with symptoms"
  temporal:   yes
  coverage:   no
  aggregate:  yes
  cumulative: no
  scale:      yes
  group_by:   none, age, priority_group, variant

# Total number of people currently in isolation
currently_isolated:
  label:     "Infected cases in isolation"
  temporal:   yes
  coverage:   no
  aggregate:  yes
  cumulative: no
  scale:      yes
  group_by:   none, age, priority_group, variant

# Population susceptibility (immunity weighted number of susceptibles)
pop_susceptibility:
  label:     "Population susceptibility (%)"
  temporal:   yes
  coverage:   no
  aggregate:  yes
  cumulative: no
  scale:      no
  group_by:   na

# Overall prevalence of population (currently infected)
pop_prevalence:
  label:     "Population prevalence (%)"
  temporal:   yes
  coverage:   no
  aggregate:  yes
  cumulative: no
  scale:      no
  group_by:   na

# Number of people infected thus far (number of people with antibodies as a proxy)
seroprevalence:
  label:     "Previously exposed (%)"
  temporal:   yes
  coverage:   no
  aggregate:  yes
  cumulative: no
  scale:      no
  group_by:   na

# Number of infections experienced per individual
n_infections: 
  label:     "Number of infections per person"
  temporal:   no
  coverage:   no
  aggregate:  no
  cumulative: no
  scale:      no
  group_by:   infections

# ---------------------------------------------------------
# Vaccine and treatment metrics
# ---------------------------------------------------------

# Number of people who have received all necessary doses over time
n_vaccinated:
  label:     "Number fully vaccinated"
  label_cum: "Cumulative fully vaccinated"
  temporal:   yes
  coverage:   no
  aggregate:  yes
  cumulative: yes
  scale:      yes
  group_by:   none, age, priority_group

# Cumulative number of people who have received all necessary doses
total_vaccinated:
  label:     "Total number fully vaccinated"
  temporal:   yes
  coverage:   no
  aggregate:  yes
  cumulative: no
  scale:      yes
  group_by:   none, age, priority_group

# Number of doses administered per day, including booster doses
n_doses:
  label:     "Number of vaccine doses"
  label_cum: "Cumulative vaccine doses"
  temporal:   yes
  coverage:   no
  aggregate:  yes
  cumulative: yes
  scale:      yes
  group_by:   none, age, priority_group

# Cumulative doses: equivalent to cumulative of n_doses
total_doses:
  label:     "Cumulative number of vaccine doses"
  temporal:   yes
  coverage:   no
  aggregate:  yes
  cumulative: no
  scale:      yes
  group_by:   none, age, priority_group

# Vaccine coverage: eligible defined by 'priority_groups', everyone gets all necessary doses
vaccine_coverage:
  label:     "Vaccination coverage (% of eligible)"
  temporal:   yes
  coverage:   yes
  aggregate:  no
  cumulative: no
  scale:      no
  group_by:   none, priority_group

# Vaccine coverage among entire population
vaccine_coverage_pop:
  label:     "Vaccination coverage (% of population)"
  temporal:   yes
  coverage:   yes
  aggregate:  no
  cumulative: no
  scale:      no
  group_by:   none, priority_group

# Booster coverage: one or more boosters ever received among those vaccinated
booster_coverage:
  label:     "Booster coverage (% of eligible)"
  temporal:   yes
  coverage:   yes
  aggregate:  no
  cumulative: no
  scale:      no
  group_by:   none, priority_group

# Booster coverage among entire population
booster_coverage_pop:
  label:     "Booster coverage (% of population)"
  temporal:   yes
  coverage:   yes
  aggregate:  no
  cumulative: no
  scale:      no
  group_by:   none, priority_group

# Booster coverage in past year among those vaccinated
booster_coverage_12m:
  label:     "Booster past 12 months (% of eligible)"
  temporal:   yes
  coverage:   yes
  aggregate:  no
  cumulative: no
  scale:      no
  group_by:   none, priority_group

# Booster coverage in past year among entire population
booster_coverage_12m_pop:
  label:     "Booster past 12 months (% of population)"
  temporal:   yes
  coverage:   yes
  aggregate:  no
  cumulative: no
  scale:      no
  group_by:   none, priority_group

# Number of people receiving PrEP per day
n_prep:
  label:     "Number of people receiving PrEP"
  label_cum: "Cumulative number receiving PrEP"
  temporal:   yes
  coverage:   no
  aggregate:  yes
  cumulative: yes
  scale:      yes
  group_by:   none, age, priority_group

# Cumulative version of the above
total_prep:
  label:     "Total number of people receiving PrEP"
  temporal:   yes
  coverage:   no
  aggregate:  yes
  cumulative: no
  scale:      yes
  group_by:   none, age, priority_group

# Prep coverage among those eligible (ie those unsuitable for vaccination)
prep_coverage:
  label:     "PrEP coverage (% of eligible)"
  temporal:   yes
  coverage:   yes
  aggregate:  no
  cumulative: no
  scale:      no
  group_by:   none, priority_group

# Prep coverage across whole population
prep_coverage_pop:
  label:     "PrEP coverage (% of population)"
  temporal:   yes
  coverage:   yes
  aggregate:  no
  cumulative: no
  scale:      no
  group_by:   none, priority_group

# Total number of treatments per day: successful or not
n_treat:
  label:     "Number of treatment doses per day"
  label_cum: "Cumulative number of treatment doses"
  temporal:   yes
  coverage:   no
  aggregate:  yes
  cumulative: yes
  scale:      yes
  group_by:   none, age, priority_group

# Cumulative version of the above
total_treat:
  label:     "Cumulative number of treatment doses"
  temporal:   yes
  coverage:   no
  aggregate:  yes
  cumulative: no
  scale:      yes
  group_by:   none, age, priority_group

# Number of people successfully treated per day: a subset of those treated
n_treat_success:
  label:     "Successfully treated per day"
  label_cum: "Cumulative successful treatments"
  temporal:   yes
  coverage:   no
  aggregate:  yes
  cumulative: yes
  scale:      yes
  group_by:   none, age, priority_group

# Cumulative version of the above
total_treat_success:
  label:     "Cumulative successful treatments"
  temporal:   yes
  coverage:   no
  aggregate:  yes
  cumulative: no
  scale:      yes
  group_by:   none, age, priority_group

# NOT YET IMPLEMENTED
treatment_coverage:
  label:     "Treatment coverage (% of eligible)"
  temporal:   yes
  coverage:   yes
  aggregate:  no
  cumulative: no
  scale:      no
  group_by:   none, priority_group

# NOT YET IMPLEMENTED
treatment_coverage_pop:
  label:     "Treatment coverage (% of  population)"
  temporal:   yes
  coverage:   yes
  aggregate:  no
  cumulative: no
  scale:      no
  group_by:   none, priority_group
  
# ---------------------------------------------------------
# Health economic metrics
# ---------------------------------------------------------

# TODO: Allow disaggregation by priority_group

# Cost of hospitalisation and ICU events
healthcare_costs:
  label:     "Healthcare-related costs"
  label_cum: "Cumulative healthcare costs"
  temporal:   yes
  coverage:   no
  aggregate:  yes
  cumulative: yes
  scale:      yes
  group_by:   na # none, priority_groups
  
# Cost per pharmaceutical interventions: vaccines, prep, and treatment
intervention_costs:
  label:     "Intervention-related costs"
  label_cum: "Cumulative intervention costs"
  temporal:   yes
  coverage:   no
  aggregate:  yes
  cumulative: yes
  scale:      yes
  group_by:   na # none, priority_groups

# Overall costs (intervention_costs + healthcare_costs)
overall_costs:
  label:     "Overall costs"
  label_cum: "Cumulative overall costs"
  temporal:   yes
  coverage:   no
  aggregate:  yes
  cumulative: yes
  scale:      yes
  group_by:   na
