---

# xxx
state_flows:
# New infections: susceptible -> latent
- disease_state: susc
  care_state: none
  prognosis_state: none
  next_disease: latent
  next_care: none
  next_duration: "latency"
# Latent cases -> pre-symptomatic
- disease_state: latent
  care_state: none
  prognosis_state: asym  # For asym cases
  next_disease: presym
  next_care: none
  next_duration: "presymptomatic"
- disease_state: latent
  care_state: none
  prognosis_state: mild  # For mild cases
  next_disease: presym
  next_care: none
  next_duration: "presymptomatic"
- disease_state: latent
  care_state: none
  prognosis_state: severe_care  # For severe (in care) cases
  next_disease: presym
  next_care: none
  next_duration: "presymptomatic"
- disease_state: latent
  care_state: none
  prognosis_state: crit_care  # For critical (in care) cases
  next_disease: presym
  next_care: none
  next_duration: "presymptomatic"
- disease_state: latent
  care_state: none
  prognosis_state: dead_care  # For deaths (in care)
  next_disease: presym
  next_care: none
  next_duration: "presymptomatic"
- disease_state: latent
  care_state: none
  prognosis_state: severe_home  # For severe (stay at home) cases
  next_disease: presym
  next_care: none
  next_duration: "presymptomatic"
- disease_state: latent
  care_state: none
  prognosis_state: crit_home  # For severe (stay at home) cases
  next_disease: presym
  next_care: none
  next_duration: "presymptomatic"
- disease_state: latent
  care_state: none
  prognosis_state: dead_home  # For deaths (at home)
  next_disease: presym
  next_care: none
  next_duration: "presymptomatic"
# Pre-symptomatic -> a/symptomatic
- disease_state: presym
  care_state: none
  prognosis_state: asym  # For asym cases
  next_disease: asym
  next_care: none
  next_duration: "infectious_mild"
- disease_state: presym
  care_state: none
  prognosis_state: mild  # For mild cases
  next_disease: mild
  next_care: none
  next_duration: "infectious_mild"
- disease_state: presym
  care_state: none
  prognosis_state: severe_care  # For severe (in care) cases
  next_disease: severe
  next_care: none
  next_duration: "onset_to_hospital"
- disease_state: presym
  care_state: none
  prognosis_state: crit_care  # For critical (in care) cases
  next_disease: severe
  next_care: none
  next_duration: "onset_to_hospital"
- disease_state: presym
  care_state: none
  prognosis_state: dead_care  # For deaths (in care)
  next_disease: severe
  next_care: none
  next_duration: "onset_to_hospital"
- disease_state: presym
  care_state: none
  prognosis_state: severe_home  # For severe (stay at home) cases
  next_disease: severe
  next_care: none
  next_duration: "infectious_severe"
- disease_state: presym
  care_state: none
  prognosis_state: crit_home  # For severe (stay at home) cases
  next_disease: crit
  next_care: none
  next_duration: "infectious_severe"
- disease_state: presym
  care_state: none
  prognosis_state: dead_home  # For deaths (at home)
  next_disease: crit
  next_care: none
  next_duration: "home_death"
# Recovery of non-severe cases
- disease_state: asym
  care_state: none
  prognosis_state: asym  # Recovery for asym cases
  next_disease: susc
  next_care: none
  metric: "recovered"
- disease_state: mild
  care_state: none
  prognosis_state: mild  # Recovery for mild cases
  next_disease: susc
  next_care: none
  metric: "recovered"
# Recovery during/after isolation period
- disease_state: latent
  care_state: iso
  prognosis_state: asym  # Asymptomatic cases (in latent stage)
  next_disease: susc
  next_care: none
  metric: "recovered"
- disease_state: latent
  care_state: iso
  prognosis_state: mild  # Mild cases (in latent stage)
  next_disease: susc
  next_care: none
  metric: "recovered"
- disease_state: presym
  care_state: iso
  prognosis_state: asym  # Asymptomatic cases (in presym stage)
  next_disease: susc
  next_care: none
  metric: "recovered"
- disease_state: presym
  care_state: iso
  prognosis_state: mild  # Mild cases (in presym stage)
  next_disease: susc
  next_care: none
  metric: "recovered"
- disease_state: asym
  care_state: iso
  prognosis_state: asym  # Asymptomatic cases
  next_disease: susc
  next_care: none
  metric: "recovered"
- disease_state: mild
  care_state: iso
  prognosis_state: mild  # Mild cases
  next_disease: susc
  next_care: none
  metric: "recovered"
# Severe cases -> hospital or recovery
- disease_state: severe
  care_state: none
  prognosis_state: severe_care  # Severe prognosis (in care)
  next_disease: severe
  next_care: hospital
  next_duration: "hospital_stay"
  metric: "hospital_admissions"
- disease_state: severe
  care_state: none
  prognosis_state: crit_care  # Critical prognosis (in care)
  next_disease: severe
  next_care: hospital
  next_duration: "hospital_to_icu"
  metric: "hospital_admissions"
- disease_state: severe
  care_state: none
  prognosis_state: dead_care  # Death prognosis (in care)
  next_disease: severe
  next_care: hospital
  next_duration: "hospital_to_icu"
  metric: "hospital_admissions"
- disease_state: severe
  care_state: none
  prognosis_state: severe_home  # Severe prognosis (stay at home)
  next_disease: susc
  next_care: none
  metric: "recovered"
# Hopsital cases -> ICU or recovery
- disease_state: severe
  care_state: hospital
  prognosis_state: severe_care  # Severe prognosis (stay at home)
  next_disease: susc
  next_care: none
  metric: "recovered"
- disease_state: severe
  care_state: hospital
  prognosis_state: crit_care  # Critical prognosis (in care)
  next_disease: crit
  next_care: icu
  next_duration: "icu_stay"
  metric: "icu_admissions"
- disease_state: severe
  care_state: hospital
  prognosis_state: dead_care  # Death prognosis (in care)
  next_disease: crit
  next_care: icu
  next_duration: "icu_stay_death"
  metric: "icu_admissions"
# Critical cases -> death or recovery
- disease_state: crit
  care_state: icu
  prognosis_state: crit_care  # Critical prognosis (in care)
  next_disease: severe
  next_care: rehosp
  next_duration: "hospital_transfer"
- disease_state: crit
  care_state: icu
  prognosis_state: dead_care  # Death prognosis (in care)
  next_disease: dead
  next_care: none
  metric: "deaths"
- disease_state: crit
  care_state: none
  prognosis_state: crit_home  # Critical prognosis (stay at home)
  next_disease: susc
  next_care: none
  metric: "recovered"
- disease_state: crit
  care_state: none
  prognosis_state: dead_home  # Death prognosis (stay at home)
  next_disease: dead
  next_care: none
  metric: "deaths"
# Recovery following ICU
- disease_state: severe
  care_state: rehosp
  prognosis_state: crit_care  # Critical prognosis (in care)
  next_disease: susc
  next_care: none
  metric: "recovered"
# Replace dead with new susceptibles
- disease_state: dead
  care_state: none
  prognosis_state: dead_care  # Death prognosis (in care)
  next_disease: susc
  next_care: none
  metric: "recovered"
- disease_state: dead
  care_state: none
  prognosis_state: dead_home  # Death prognosis (at home)
  next_disease: susc
  next_care: none
  metric: "recovered"

